Repository Homebrew/homebrew-cask, pull requests merged in 2018-04, with the labels that each got.

#45327 travis.yml: travis buddy
  .travis.yml
  developer/bin/sync_templates_and_ci
Labels: travis

#45154 pkg.md, rejected_casks.md: allow_untrusted
  doc/cask_language_reference/stanzas/pkg.md
  doc/faq/rejected_casks.md
Labels: documentation

#45464 Update adobe-photoshop-lightroom: uninstall preflight
  Casks/adobe-photoshop-lightroom.rb
Labels: on hold

#45637 Add parts-library caveats to Fritzing 0.9.3b
  Casks/fritzing.rb
Labels: awaiting maintainer feedback, on hold

#45696 Update Transmission Remote GUI to v5.15.4
  Casks/transmission-remote-gui.rb
Labels: awaiting user reply

#45787 ISSUE_TEMPLATE.md: ask for specific command
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#45592 Update aptanastudio to 3.6.1
  Casks/aptanastudio.rb
Labels: awaiting user reply

#45939 Remove travis buddy
  .travis.yml
Labels: awaiting maintainer feedback, travis

#46018 Update castbridge to 1.0.5
  Casks/castbridge.rb
Labels: awaiting user reply, awaiting verification

#46112 rejected_casks: increase threshold to 50 stars
  doc/faq/rejected_casks.md
Labels: awaiting maintainer feedback

#46214 Fix checksum: persepolis-download-manager 3.1.0
  Casks/persepolis-download-manager.rb
Labels: awaiting verification

#46417 note that some Casks don't show up as outdated
  USAGE.md
Labels: documentation

#46408 Update rambox to 0.5.17
  Casks/rambox.rb
Labels: awaiting user reply, on hold

#46468 Update mactex, mactex-no-gui to 2018.0417
  Casks/mactex-no-gui.rb
  Casks/mactex.rb
Labels: on hold, upstream
