Repository Homebrew/homebrew-cask, pull requests merged in 2018-05, with the labels that each got.

#46721 Configure No Response bot
  .github/no-response.yml
Labels: meta

#46797 Update minizincide to 2.1.7
  Casks/minizincide.rb
Labels: awaiting user reply

#44751 travis.yml: xcode9.3
  .travis.yml
  ci/travis/script.sh
Labels: travis

#47108 issue templates
  developer/bin/update_issue_template_urls
  doc/issue_templates/issue_dead_app.md
  doc/issue_templates/issue_outdated_cask.md
  doc/issue_templates/issue_outdated_cask_but_cannot_find_link.md
  doc/issue_templates/issue_source_not_there_and_cannot_find_it.md
  doc/issue_templates/issue_wrong_number_of_arguments.md
  doc/reporting_bugs/checksum_does_not_match_error_fix_outdated.md
  doc/reporting_bugs/curl_error_fix_no_download.md
  doc/reporting_bugs/curl_error_fix_outdated.md
  doc/reporting_bugs/source_is_not_there_fix.md
  doc/reporting_bugs/wrong_number_of_arguments_fix.md
Labels: documentation

#47257 Update token reference
  doc/cask_language_reference/token_reference.md
Labels: documentation

#47291 caveats mini-dsl: use quotes instead of parenthesis
  doc/cask_language_reference/stanzas/caveats.md
Labels: documentation

#47107 Update qtox to 1.15.0
  Casks/qtox.rb
Labels: awaiting user reply, awaiting verification

#47290 caveats: add license
  doc/cask_language_reference/stanzas/caveats.md
Labels: documentation

#47261 Update 7 Casks: change to license caveat DSL
  Casks/anka-build.rb
  Casks/anka-flow.rb
  Casks/intel-haxm.rb
  Casks/java-jdk-javadoc.rb
  Casks/java.rb
  Casks/sencha.rb
  Casks/virtualbox-extension-pack.rb
Labels: on hold

#47465 Update synergy to 2.0.12,b1807-50472cde
  Casks/synergy.rb
Labels: awaiting maintainer feedback

#47530 Update epic-games to 7.9.4
  Casks/epic-games.rb
Labels: awaiting verification

#47765 rejected_casks: improve wording on submitting to homebrew/core
  doc/faq/rejected_casks.md
Labels: documentation

#47771 Update th-makerx to 4.0.0
  Casks/th-makerx.rb
Labels: awaiting user reply

#47603 Add Clock.saver screensaver v0.5.0
  Casks/clocksaver.rb
Labels: awaiting user reply

#47901 Update lulu to 0.9.5
  Casks/lulu.rb
Labels: on hold

#47909 Remove elm-platform
  Casks/elm-platform.rb
Labels: awaiting maintainer feedback, on hold
