Repository Homebrew/homebrew-cask, pull requests merged in 2018-06, with the labels that each got.

#48097 rejected_casks.md: clarify formulas are to be built from source
  doc/faq/rejected_casks.md
Labels: documentation

#48100 Add Mojave references
  doc/cask_language_reference/readme.md
  doc/cask_language_reference/stanzas/depends_on.md
  doc/development/adding_a_cask.md
Labels: documentation

#48235 docs: remove appcast checkpoints
  CONTRIBUTING.md
  doc/cask_language_reference/readme.md
  doc/cask_language_reference/stanzas/appcast.md
  doc/development/adding_a_cask.md
Labels: documentation

#48327 script: readd gpg
  ci/travis/script.sh
Labels: travis

#48553 token_reference: add links to tap specific naming conventions
  doc/cask_language_reference/token_reference.md
Labels: documentation

#48566 contributing: update versions reference
  CONTRIBUTING.md
Labels: documentation

#48562 travis.yml: xcode 9.4
  .travis.yml
Labels: travis

#48437 Fixed wrong Checksum for camunda-modeler
  Casks/camunda-modeler.rb
Labels: awaiting verification

#46749 Update IDA free 7.0 SHA
  Casks/idafree.rb
Labels: awaiting maintainer feedback

#48567 cask_language_reference version: add `minor_patch`
  doc/cask_language_reference/stanzas/version.md
Labels: documentation

#48755 usage: cask completions
  USAGE.md
Labels: documentation

#48944 Update silverback to 3.1.8,237:1516782103
  Casks/silverback.rb
Labels: awaiting user reply

#48561 Update adguard to 1.5.8
  Casks/adguard.rb
Labels: awaiting verification

#48021 Fix checksum in MCGimp-std
  Casks/mcgimp-std.rb
Labels: awaiting verification

#48941 Delete lastpass.rb
  Casks/lastpass.rb
Labels: awaiting maintainer feedback
