Repository Homebrew/homebrew-cask, pull requests merged in 2018-10, with the labels that each got.

#52909 Update keymo to 1.2.6
  Casks/keymo.rb
  Casks/keymou.rb
Labels: awaiting maintainer feedback

#52542 Add Mathpix 1.3.48
  Casks/mathpix-snipping-tool.rb
Labels: awaiting maintainer feedback

#52505 Add Retrobatch.app v1.1
  Casks/retrobatch.rb
Labels: awaiting maintainer feedback

#52683 qt3dstudio v2.1.0 - new cask
  Casks/qt3dstudio.rb
Labels: awaiting maintainer feedback

#52893 libreoffice-language-pack: install manually
  Casks/libreoffice-language-pack.rb
Labels: awaiting maintainer feedback

#53561 coconutbattery 3.7.1: fix checksum
  Casks/coconutbattery.rb
Labels: awaiting user reply

#51713 Add shadowsocksx-ng-r.app v1.4.3-R8-build3
  Casks/shadowsocksx-ng-r.rb
Labels: awaiting maintainer feedback

#53588 Add Dozer.app v1.1.3
  Casks/dozer.rb
Labels: new cask

#50871 Update splashtop-streamer to 3.2.6.0
  Casks/splashtop-streamer.rb
Labels: awaiting maintainer feedback

#53751 corrected checksum for XCA 2.1.1 download
  Casks/xca.rb
Labels: awaiting verification

#54190 Add Dynamic-Dark-Mode v1.0.6, a dark mode modulator for mac
  Casks/dynamic.rb
Labels: awaiting user reply, new cask

#54226 Added Ocelot v3.0 Cask
  Casks/ocelot.rb
Labels: new cask

#54225 Added SquadAnimator Gaelic Football/Hurling (GAA) v1.0.2 Cask
  Casks/squadanimator-gaa.rb
Labels: new cask

#54224 Added SquadAnimator Rugby v1.0.1 Cask
  Casks/squadanimator-rugby.rb
Labels: new cask

#54223 Added SquadAnimator Soccer Cask
  Casks/squadanimator.rb
Labels: new cask
