Repository Homebrew/homebrew-cask, pull requests merged in 2019-01, with the labels that each got.

#56971 Add Cricut Design Space Plugin 5.8.1808.282223
  Casks/cricut-design-space.rb
Labels: awaiting user reply

#56816 Update dotnet-sdk 2.2.100: remove /etc/paths.d/dotnet-cli-tools
  Casks/dotnet-sdk.rb
Labels: awaiting user reply

#57168 Update MEGAsync to 3.7.1
  Casks/megasync.rb
Labels: awaiting maintainer feedback

#57073 Update minecraftpe to 1-7-release-20181106
  Casks/minecraftpe.rb
Labels: upstream

#56972 Adding Criptext 0.14.7
  Casks/criptext.rb
Labels: awaiting user reply

#57487 Update googleappengine to 1.9.81
  Casks/googleappengine.rb
Labels: awaiting user reply

#57844 Revamp reporting bugs docs
  .github/ISSUE_TEMPLATE/01_bug_report.md
  README.md
  doc/reporting_bugs/checksum_does_not_match_error.md
  doc/reporting_bugs/checksum_does_not_match_error_fix_icomplete.md
  doc/reporting_bugs/checksum_does_not_match_error_fix_outdated.md
  doc/reporting_bugs/curl_error.md
  doc/reporting_bugs/curl_error_fix_curlrc.md
  doc/reporting_bugs/curl_error_fix_no_download.md
  doc/reporting_bugs/curl_error_fix_outdated.md
  doc/reporting_bugs/curl_error_fix_vendor.md
  doc/reporting_bugs/curl_error_fix_wont_fix.md
  doc/reporting_bugs/error_examples.md
  doc/reporting_bugs/error_unknown_command_cask.md
  doc/reporting_bugs/permission_denied_error.md
  doc/reporting_bugs/permission_denied_error_fix_appdir.md
  doc/reporting_bugs/permission_denied_error_fix_bundle.md
  doc/reporting_bugs/source_is_not_there_error.md
  doc/reporting_bugs/uninstall_wrongly_reports_cask_as_not_installed.md
  doc/reporting_bugs/wrong_number_of_arguments_error.md
  doc/reporting_bugs/wrong_number_of_arguments_fix.md
Labels: documentation

#58000 Update slack to 3.3.7
  Casks/slack.rb
Labels: awaiting user reply
