Repository Homebrew/homebrew-cask, pull requests merged in 2019-08, with the labels that each got.

#66957 Add XCTU Latest
  Casks/xctu.rb
Labels: awaiting user reply

#67456 rejected_casks.md: expand "too obscure"
  doc/faq/rejected_casks.md
Labels: documentation

#66498 Burp Suite 2.1: fix permissions, ownership
  Casks/burp-suite.rb
Labels: upstream

#68156 Add Runway ML
  Casks/celestialteapot-runway.rb
  Casks/runway.rb
Labels: awaiting user reply

#68165 new: Netiquette 1.0.0
  Casks/netiquette.rb
Labels: awaiting user reply
