Repository Homebrew/homebrew-cask, pull requests merged in 2020-11, with the labels that each got.

#91875 Add Pitch.app v1.2.2
  Casks/pitch.rb
Labels: awaiting user reply

#91998 Update megasync from 4.3.6 to 4.3.7
  Casks/megasync.rb
Labels: ci-skip-appcast

#92043 add overflowio
  Casks/protoio-overflow.rb
Labels: awaiting user reply

#92091 Update vrew from 0.6.1 to 0.6.2
  Casks/vrew.rb
Labels: ci-skip-install

#92111 Delete aliwangwang.rb
  Casks/aliwangwang.rb
Labels: awaiting maintainer feedback

#92196 Update chromium from 822990 to 825209
  Casks/chromium.rb
Labels: ci-skip-appcast

#92193 Update nightowl from 0.2.9 to 0.3.0
  Casks/nightowl.rb
Labels: ci-skip-appcast

#92224 Update freac from 1.1.3 to 1.1.3a
  Casks/freac.rb
Labels: ci-skip-appcast

#92200 Update iridium
  Casks/iridium.rb
Labels: ci-skip-install

#92284 Update rescuetime from 2.16.5.1 to 2.16.6.1
  Casks/rescuetime.rb
Labels: ci-skip-appcast

#92250 Update iina from 1.1.0 to 1.1.1
  Casks/iina.rb
Labels: ci-skip-appcast

#92303 Update flash-player-debugger from 32.0.0.445 to 32.0.0.453
  Casks/flash-player-debugger.rb
Labels: ci-retry

#92302 Update flash-player from 32.0.0.445 to 32.0.0.453
  Casks/flash-player.rb
Labels: ci-retry

#92305 Update flash-player-debugger-ppapi from 32.0.0.445 to 32.0.0.453
  Casks/flash-player-debugger-ppapi.rb
Labels: ci-retry

#92315 Update hbuilderx from 2.9.3.20201014 to 2.9.8.20201110
  Casks/hbuilderx.rb
Labels: ci-skip-appcast

#92367 Update bettertouchtool from 3.404-1635 to 3.502-1639
  Casks/bettertouchtool.rb
Labels: ci-skip-appcast

#92383 USAGE.md: fix manpage name
  USAGE.md
Labels: documentation

#88682 USAGE.md: various updates
  USAGE.md
Labels: documentation

#92391 Update bettertouchtool from 3.502-1639 to 3.503-1640
  Casks/bettertouchtool.rb
Labels: ci-skip-appcast

#92472 Update malus from 1.5.0 to 1.5.1
  Casks/malus.rb
Labels: ci-skip-appcast

#92579 Revert "Update nvidia-geforce-now from 2.0.24.105,8F16A9 to 2.0.25.119,8F16A9"
  Casks/nvidia-geforce-now.rb
Labels: ci-skip-appcast, ci-skip-install

#92666 owasp-zap: add description
  Casks/owasp-zap.rb
Labels: ci-skip-appcast

#92729 Update prowritingaid from 2.0.47 to 2.0.48
  Casks/prowritingaid.rb
Labels: ci-skip-appcast

#92788 Fix RuboCop offenses.
  Casks/4k-youtube-to-mp3.rb
  Casks/autodesk-fusion360.rb
  Casks/banking-4.rb
  Casks/bitrix24.rb
  Casks/blobby-volley2.rb
  Casks/ev3-classroom.rb
  Casks/gns3.rb
  Casks/go64.rb
  Casks/guild-wars2.rb
  Casks/icons8.rb
  Casks/ioquake3.rb
  Casks/iterm2.rb
  Casks/jtool2.rb
  Casks/kdiff3.rb
  Casks/kid3.rb
  Casks/lego-mindstorms-ev3.rb
  Casks/listen1.rb
  Casks/marathon2.rb
  Casks/multiscan-3b.rb
  Casks/neo4j.rb
  Casks/perimeter81.rb
  Casks/saoimageds9.rb
  Casks/tipp10.rb
  Casks/v2rayx.rb
  Casks/virtualc64.rb
  Casks/windows95.rb
Labels: ci-syntax-only

#92833 Update noxappplayer from 3.8.1.0,20201014:0ea933d044244d13ab6472611973b163 to 3.8.5.0,20201113:05630baf34354e2f9c57162b8f3db659
  Casks/noxappplayer.rb
Labels: ci-skip-appcast

#92852 Update arq from 6.2.66 to 6.2.68
  Casks/arq.rb
Labels: ci-skip-appcast

#92780 Add Starsector 0.9.1a-RC8
  Casks/starsector.rb
Labels: awaiting user reply

#93002 Update native-access from 1.13.0.133 to 1.13.1.134
  Casks/native-access.rb
Labels: ci-skip-appcast

#93007 Update messenger from 75.4.124,252571813 to 78.4.114,257025287
  Casks/messenger.rb
Labels: ci-skip-appcast

#92994 Update bettertouchtool from 3.505-1643 to 3.506-1644
  Casks/bettertouchtool.rb
Labels: ci-skip-appcast

#93094 Update tap-forms from 5.3.14 to 5.3.16
  Casks/tap-forms.rb
Labels: ci-skip-appcast

#93072 Add cask 'iconset'
  Casks/iconset.rb
Labels: ci-syntax-only

#93120 depends_on: add big_sur
  doc/cask_language_reference/stanzas/depends_on.md
Labels: documentation

#93139 Update messenger from 78.4.114,257025287 to 78.5.114,257405162
  Casks/messenger.rb
Labels: ci-skip-appcast

#93103 zap.md: prepare for new invocation
  doc/cask_language_reference/stanzas/zap.md
Labels: documentation

#93248 chrome-remote-desktop-host.rb: add Google to desc
  Casks/chrome-remote-desktop-host.rb
Labels: ci-syntax-only

#93091 Update megasync from 4.3.7 to 4.3.8
  Casks/megasync.rb
Labels: ci-skip-appcast

#93316 Update chromium from 827706 to 830002
  Casks/chromium.rb
Labels: ci-skip-appcast

#93426 Update duet from 2.3.1.8 to 2.3.2.6
  Casks/duet.rb
Labels: ci-skip-appcast

#93383 Update family-tree-builder to 8.2.0.8521 (Support of Catalina)
  Casks/family-tree-builder.rb
Labels: ci-skip-appcast

#93437 PULL_REQUEST_TEMPLATE: update commands to run
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#93438 rejected casks: obscure: remove reference to self-submitted
  doc/faq/rejected_casks.md
Labels: documentation

#93570 Update dcommander from 3870 to 3881
  Casks/dcommander.rb
Labels: ci-skip-appcast

#93444 zoomus.rb: add comment on auto_updates
  Casks/zoom-for-it-admins.rb
  Casks/zoomus.rb
Labels: awaiting maintainer feedback

#93636 Add Nota.app v0.19
  Casks/nota.rb
Labels: ci-syntax-only

#93739 Update naver-whale.rb
  Casks/naver-whale.rb
Labels: ci-skip-appcast, ci-skip-install, ci-syntax-only

#93787 README.md: update gif and installation for lack of `cask`
  README.md
Labels: documentation

#93798 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#93810 Update mp3tag
  Casks/mp3tag.rb
Labels: ci-skip-appcast

#93826 Update chromium from 830002 to 831698
  Casks/chromium.rb
Labels: ci-skip-appcast

#93894 PULL_REQUEST_TEMPLATE.md: move technical commands for last
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#93934 Update numi from 3.28.668 to 3.29.680
  Casks/numi.rb
Labels: ci-skip-appcast
