Repository Homebrew/homebrew-cask, pull requests merged in 2020-05, with the labels that each got.

#81778 dangerzone 0.1.1
  Casks/dangerzone.rb
Labels: awaiting user reply

#82418 Update loginputmac from 2.3.5 to 2.3.5_1
  Casks/loginputmac.rb
Labels: awaiting user reply

#82267 Add Play! latest formula
  Casks/purei-play.rb
Labels: awaiting user reply

#82026 Modify Navicat Premium to support Chinese version
  Casks/navicat-premium.rb
Labels: awaiting user reply

#82587 update lightproxy.app to 1.1.15
  Casks/lightproxy.rb
Labels: awaiting user reply

#81545 FAQ: why some apps are not included in `upgrade`
  doc/faq/app_not_upgrading.md
Labels: documentation

#83068 Add Accurics CLI
  Casks/accurics-cli.rb
Labels: awaiting user reply

#83120 Update sha in houdahspot.rb
  Casks/houdahspot.rb
Labels: awaiting maintainer feedback

#81265 rejected_casks.md: update notability requirements
  doc/faq/rejected_casks.md
Labels: documentation

#83151 Add MPLAB X IDE
  Casks/mplabx-ide.rb
Labels: awaiting user reply

#83304 Update Engine Prime from 1.3.4 to 1.5.0
  Casks/engine-prime.rb
Labels: awaiting user reply

#83356 update switchresx.rb to v4.10.0
  Casks/switchresx.rb
Labels: awaiting user reply

#83305 Update numi from 3.27.665 to 3.28.668
  Casks/numi.rb
Labels: awaiting user reply

#83423 Update free-download-manager from 5.1.38 to 6.9.1
  Casks/free-download-manager.rb
Labels: awaiting user reply

#83438 Update ultimate.rb from 3.0.12.428 to 3.0.12.529
  Casks/ultimate.rb
Labels: awaiting user reply

#83422 Add cask coconutID from https://www.coconut-flavour.com/coconutid/
  Casks/coconutid.rb
Labels: awaiting user reply

#83284 copyq: add caveat about Accessibility preferences
  Casks/copyq.rb
  doc/cask_language_reference/stanzas/caveats.md
Labels: do not merge
