Repository Homebrew/homebrew-cask, pull requests merged in 2020-08, with the labels that each got.

#87168 Update musescore from 3.4.2 to 3.5.0
  Casks/musescore.rb
Labels: awaiting user reply

#85850 Add Fing Desktop
  Casks/fing-desktop.rb
Labels: in progress

#88054 Update listen1 from 2.11.0 to 2.12.3
  Casks/listen1.rb
Labels: awaiting user reply

#88213 Add zprint 1.0.0
  Casks/zprint.rb
Labels: awaiting user reply

#88301 Check for `skip-install` label.
  .github/workflows/ci.yml
Labels: skip-install

#88172 Update kafka-tool from 2.0.7 to 2.0.8
  Casks/kafka-tool.rb
Labels: skip-install

#88371 Update datadog-agent from 7.21.1-1 to 7.22.0-1
  Casks/datadog-agent.rb
Labels: skip-install

#88055 Add ToolReleases.app v1.3.4
  Casks/toolreleases.rb
Labels: awaiting user reply
