Repository Homebrew/homebrew-cask, pull requests merged in 2020-03, with the labels that each got.

#77883 Add Telavox flow master v1.93.0
  Casks/telavox-flow.rb
Labels: awaiting user reply

#78036 rejected_casks.md: reject casks with no homepage info
  doc/faq/rejected_casks.md
Labels: documentation

#78263 adding_a_cask.md: forks: add exception for recommendations
  doc/development/adding_a_cask.md
Labels: documentation

#78449 Add cask 'microsoft-outlook' v16.35.20030802
  Casks/microsoft-outlook.rb
Labels: awaiting user reply

#78719 README.md: change wording on cask requests
  README.md
Labels: documentation

#78840 Add OMX eBooks Latest
  Casks/omx-ebooks.rb
Labels: awaiting user reply

#79219 GPlates 2.2.0
  Casks/gplates.rb
Labels: awaiting user reply

#79327 Update papers
  Casks/papers.rb
Labels: awaiting user reply

#79519 Upgrade iGlance.app to v2.0
  Casks/iglance.rb
Labels: awaiting user reply

#79581 Update reaper from 6.50.0,6.05 to 6.06
  Casks/reaper.rb
Labels: awaiting user reply

#79553 Add Lazy v1?
  Casks/lazy.rb
Labels: awaiting user reply

#79620 Update sound-control: the uninstall `launchctl` key does not accept wildcards. Fixes this cask
  Casks/sound-control.rb
Labels: awaiting maintainer feedback

#79679 Add Studio-Link v20.03.8
  Casks/studiolinkstandalone.rb
Labels: awaiting user reply
