Repository Homebrew/homebrew-cask, pull requests merged in 2020-07, with the labels that each got.

#85283 Update macx-dvd-ripper-pro from 6.5.2,20200420 to 6.5.3,20200630
  Casks/macx-dvd-ripper-pro.rb
Labels: awaiting user reply

#85314 libreoffice-language-pack 6.4.5
  Casks/libreoffice-language-pack.rb
Labels: awaiting user reply

#85350 Update eaccess from 1.13.1 to 1.13.2
  Casks/eaccess.rb
Labels: awaiting user reply

#85558 Update daemon-tools from 8.1.703 to 8.1.706
  Casks/daemon-tools.rb
Labels: upstream

#85364 Update language.md documentation
  doc/cask_language_reference/stanzas/language.md
Labels: documentation

#85853 Update geotag-photos-pro from 1.6.1 to 1.6.2
  Casks/geotag-photos-pro.rb
Labels: awaiting user reply

#85863 update microsoft-azure-storage-explorer to 1.14.0
  Casks/microsoft-azure-storage-explorer.rb
Labels: awaiting user reply

#86067 Add Camo Studio
  Casks/camo-studio.rb
Labels: awaiting user reply

#86119 Delete x48.rb
  Casks/x48.rb
Labels: awaiting maintainer feedback

#86216 Change container image for `BrewTestBot`
  .github/workflows/automerge.yml
Labels: awaiting maintainer feedback

#86269 fixing hash for current QGIS download
  Casks/qgis.rb
Labels: awaiting user reply

#86433 Add Gmail Desktop v2.20.0
  Casks/timche-gmail-desktop.rb
Labels: awaiting user reply

#85573 .github/workflows: run `brew cask style`.
  .github/workflows/ci.yml
Labels: awaiting maintainer feedback
