Repository Homebrew/homebrew-cask, pull requests merged in 2020-09, with the labels that each got.

#88554 Revert "Update joplin from 1.0.233 to 1.0.237"
  Casks/joplin.rb
Labels: ci-verified-manually

#88633 Update intune-company-portal from 2.7.200700 to 2.8.200800
  Casks/intune-company-portal.rb
Labels: ci-verified-manually

#88687 Add support for `ci-skip-appcast` label.
  cmd/lib/ci_matrix.rb
  cmd/lib/generate-matrix.rb
Labels: ci-skip-appcast

#88770 Update virtualbox-extension-pack from 6.1.12 to 6.1.14
  Casks/virtualbox-extension-pack.rb
Labels: ci-skip-install

#88655 Update jaxx-liberty from 2.4.5 to 2.4.6
  Casks/jaxx-liberty.rb
Labels: ci-skip-appcast

#88681 Update app_not_upgrading.md: `brew cask upgrade` -> `brew upgrade --cask`
  doc/faq/app_not_upgrading.md
Labels: documentation

#88485 Add NaverWhale v2.8.105.22
  Casks/naver-whale.rb
Labels: awaiting user reply

#88866 Update dbschema from 8.3.0 to 8.3.1
  Casks/dbschema.rb
Labels: ci-skip-appcast

#88941 Update rescuetime from 2.16.3.1 to 2.16.4.2
  Casks/rescuetime.rb
Labels: ci-skip-appcast

#88952 Revert "Update qiyimedia from 20200828,11.8.5 to 20200908,11.9.0"
  Casks/qiyimedia.rb
Labels: ci-skip-appcast

#89032 FAQ: remove GitHub mention from notability
  doc/faq/rejected_casks.md
Labels: documentation

#89077 brew bump-cask-pr above cask-repair
  CONTRIBUTING.md
  developer/bin/update_cask_family
Labels: documentation

#89086 Add MediBang Paint Pro v25.4
  Casks/medibangpaintpro.rb
Labels: awaiting user reply

#89113 Update toggl-track from 7.5.260 to 7.5.268
  Casks/toggl-track.rb
Labels: ci-syntax-only

#89141 Update yep from 3.8.5 to 4.0.0
  Casks/yep.rb
Labels: ci-skip-appcast

#89136 Add Ajour.app 0.3.2
  Casks/ajour.rb
Labels: ci-retry

#89139 Update intel-power-gadget from 3.6.0 to 3.7.0,b7b1b3e1dffd9b20
  Casks/intel-power-gadget.rb
Labels: ci-skip-install

#88901 Add duoshao.app v0.1.7
  Casks/duoshao.rb
Labels: awaiting user reply

#89207 Update accurics to 1.0.4
  Casks/accurics.rb
Labels: ci-retry

#89260 Update vmware-fusion from 11.5.6-16696540 to 12.0.0-16880131
  Casks/vmware-fusion.rb
Labels: ci-skip-appcast

#89350 mactex, mactex-no-gui: add desc
  Casks/mactex-no-gui.rb
  Casks/mactex.rb
Labels: ci-syntax-only

#89351 Update depends on catalina to vmware-fusion.rb
  Casks/vmware-fusion.rb
Labels: ci-skip-appcast

#89439 Update megasync from 4.3.3 to 4.3.5
  Casks/megasync.rb
Labels: ci-skip-appcast

#89483 Improve docs for `desc` stanza.
  doc/cask_language_reference/stanzas/desc.md
Labels: documentation

#89501 Add more examples for `binary`.
  doc/cask_language_reference/stanzas/binary.md
Labels: documentation

#89545 adding_a_cask.md: two exceptions for forks to overtake main
  doc/development/adding_a_cask.md
Labels: documentation

#89566 Update disk-drill from 3.8.975 to 3.8.977
  Casks/disk-drill.rb
Labels: ci-skip-appcast

#89336 Update cytoscape from 3.8.0 to 3.8.1
  Casks/cytoscape.rb
Labels: ci-skip-install

#89644 adding_a_cask.md: remove alehouse reference
  doc/development/adding_a_cask.md
Labels: documentation

#89634 Update firefox.rb from 80.0.1 to 81.0
  Casks/firefox.rb
Labels: ci-retry

#89716 Update native-access from 1.12.1.129 to 1.12.2.132
  Casks/native-access.rb
Labels: ci-skip-appcast

#89709 Update browserosaurus from 12.2.1 to 12.2.2
  Casks/browserosaurus.rb
Labels: ci-skip-install

#90037 New prowritingaid appcast based on web request
  Casks/prowritingaid.rb
Labels: ci-skip-appcast

#90099 Update videostream to 0.4.3
  Casks/videostream.rb
Labels: ci-skip-install
