Repository Homebrew/homebrew-cask, pull requests merged in 2020-12, with the labels that each got.

#93935 Update goodsync from 11.4.6.6 to 11.4.8.8
  Casks/goodsync.rb
Labels: ci-skip-appcast

#94078 Update casks referencing deprecated `brew cask`
  Casks/amazon-music.rb
  Casks/megacmd.rb
  Casks/prey.rb
  Casks/rstudio.rb
Labels: ci-syntax-only

#94100 Update webplotdigitizer from 4.3 to 4.4
  Casks/webplotdigitizer.rb
Labels: ci-skip-appcast

#94145 all_stanzas.md: updates for deprecated commands
  doc/cask_language_reference/all_stanzas.md
Labels: documentation

#94146 readme.md: add :big_sur
  doc/cask_language_reference/readme.md
Labels: documentation

#94144 USAGE.md: updates for deprecated commands
  USAGE.md
Labels: documentation

#94151 language.md: updates for deprecated commands and style
  doc/cask_language_reference/stanzas/language.md
Labels: documentation

#94147 app.md: style updates
  doc/cask_language_reference/stanzas/app.md
Labels: documentation

#94150 installer.md: style updates
  doc/cask_language_reference/stanzas/installer.md
Labels: documentation

#94152 pkg.md: style updates
  doc/cask_language_reference/stanzas/pkg.md
Labels: documentation

#94148 caveats.md: style updates
  doc/cask_language_reference/stanzas/caveats.md
Labels: documentation

#94149 conflicts_with.md: style updates
  doc/cask_language_reference/stanzas/conflicts_with.md
Labels: documentation

#94153 suite.md: style updates
  doc/cask_language_reference/stanzas/suite.md
Labels: documentation

#94156 version.md: style updates
  doc/cask_language_reference/stanzas/version.md
Labels: documentation

#94157 zap.md: updates for deprecated commands
  doc/cask_language_reference/stanzas/zap.md
Labels: documentation

#94155 uninstall.md: style updates
  doc/cask_language_reference/stanzas/uninstall.md
Labels: documentation

#94166 checksum_does_not_match_error.md: updates for deprecated commands
  doc/reporting_bugs/checksum_does_not_match_error.md
Labels: documentation

#94167 curl_error.md: updates for deprecated commands
  doc/reporting_bugs/curl_error.md
Labels: documentation

#94164 adding_a_cask.md: updates for deprecated commands
  doc/development/adding_a_cask.md
Labels: documentation

#94168 source_is_not_there_error.md: updates for deprecated commands and style
  doc/reporting_bugs/source_is_not_there_error.md
Labels: documentation

#94165 hacking.md: updates for deprecated commands
  doc/development/hacking.md
Labels: documentation

#94172 appcast.md: updates for deprecated commands
  doc/cask_language_reference/stanzas/appcast.md
Labels: documentation

#84607 url.md: change comment documentation to verified
  doc/cask_language_reference/stanzas/url.md
Labels: documentation

#94174 oversight: add verified, update caveats
  Casks/oversight.rb
Labels: ci-syntax-only

#94223 Update disk-drill from 4.0.130 to 4.1.206
  Casks/disk-drill.rb
Labels: ci-skip-appcast

#94250 adding_a_cask.md: remove protocol from verified
  doc/development/adding_a_cask.md
Labels: documentation

#94251 oversight.rb: remove protocol from verified
  Casks/oversight.rb
Labels: ci-syntax-only

#94241 Update recordit.rb
  Casks/recordit.rb
Labels: ci-skip-appcast

#94296 Update teamdrive.rb from 4.6.11.2725 to 4.6.12.2788 + update url
  Casks/teamdrive.rb
Labels: ci-skip-appcast

#94365 language.md: fix for new style
  doc/cask_language_reference/stanzas/language.md
Labels: documentation

#94327 Update connectiq from 3.1.8-2020-05-01-5a72d0ab2 to 3.2.3-2020-10-13-…
  Casks/connectiq.rb
Labels: awaiting user reply

#94590 Update wormhole from 1.4.7 to 1.4.8
  Casks/wormhole.rb
Labels: ci-skip-appcast

#94592 Update iterm2 from 3.4.2 to 3.4.3
  Casks/iterm2.rb
Labels: ci-skip-appcast

#94950 Update messenger from 78.5.114,257405162 to 81.6.118,261169871
  Casks/messenger.rb
Labels: ci-skip-appcast

#94969 Update crystalmaker from 10.5.5 to 10.6.0
  Casks/crystalmaker.rb
Labels: ci-skip-appcast

#94980 wine-stable: remove conflicts_with formula
  Casks/wine-stable.rb
Labels: ci-skip-appcast

#94981 Update trainerroad from 2020.47.112 to 2020.47.3.117
  Casks/trainerroad.rb
Labels: ci-skip-appcast

#94989 Update kotlin-native from 1.4.20 to 1.4.21
  Casks/kotlin-native.rb
Labels: ci-skip-appcast

#94994 Update houdahspot from 5.1.6 to 6.0
  Casks/houdahspot.rb
Labels: ci-skip-appcast

#94986 Update lingon-x from 8.0 to 8.0.1
  Casks/lingon-x.rb
Labels: ci-skip-appcast

#94995 Update p4v.rb from 20.2,2028073 to 20.3,2048092
  Casks/p4v.rb
Labels: ci-skip-appcast

#94982 Update mactracker from 7.10 to 7.10.1
  Casks/mactracker.rb
Labels: ci-skip-appcast

#95004 Update cocktail.rb to 14.0 + add big sur case
  Casks/cocktail.rb
Labels: ci-skip-appcast

#94988 Update ringcentral from 20.4.20 to 20.4.30
  Casks/ringcentral.rb
Labels: ci-skip-appcast

#94991 Update a-better-finder-attributes from 7.05 to 7.06
  Casks/a-better-finder-attributes.rb
Labels: ci-skip-appcast

#95172 Update razorsql from 9.2.5 to 9.2.6
  Casks/razorsql.rb
Labels: ci-skip-appcast

#93723 Add Spark AR Studio.app v102.0
  Casks/spark-ar-studio.rb
Labels: awaiting user reply

#95204 adding_a_cask.md: remove mentions to :latest
  doc/development/adding_a_cask.md
Labels: documentation

#95199 Mark Messenger.app as auto-updating
  Casks/messenger.rb
Labels: ci-skip-appcast

#95194 Update daedalus-mainnet from 2.6.0 to 3.0.0
  Casks/daedalus-mainnet.rb
Labels: ci-skip-appcast

#95208 version.md: mention :latest
  doc/cask_language_reference/stanzas/version.md
Labels: documentation

#95209 all_stanzas.md: remove mention to :latest
  doc/cask_language_reference/all_stanzas.md
Labels: documentation

#95210 app_not_upgrading.md: move `:latest` reference to docs
  doc/faq/app_not_upgrading.md
Labels: documentation

#95234 Update modern-csv from 1.3.11 to 1.3.13
  Casks/modern-csv.rb
Labels: ci-skip-appcast

#95238 Refer to GitHub Discussions instead of discourse
  README.md
Labels: documentation

#86432 Make `zap` a requirement
  doc/cask_language_reference/stanzas/zap.md
  doc/development/adding_a_cask.md
Labels: awaiting maintainer feedback, documentation, stale

#95353 Update razorsql from 9.2.6 to 9.2.7
  Casks/razorsql.rb
Labels: ci-skip-appcast

#95320 Update firestorm from 6.3.9.58205 to 6.4.12.62831
  Casks/firestorm.rb
Labels: ci-skip-appcast

#94943 Update launchcontrol from 1.51 to 1.51.1
  Casks/launchcontrol.rb
Labels: awaiting maintainer feedback

#95388 Update dcommander from 3.8.8,3880 to 3.8.8,3881
  Casks/dcommander.rb
Labels: ci-skip-appcast

#95384 Update back-in-time from 5.1.4 to 5.1.5
  Casks/back-in-time.rb
Labels: ci-skip-appcast

#95418 Add cask "youtube-downloader" v0.7
  Casks/youtube-downloader.rb
Labels: awaiting user reply

#95483 depends_on.md: remove reference to x11
  doc/cask_language_reference/stanzas/depends_on.md
Labels: documentation

#95740 repair how to create new cask
  doc/development/adding_a_cask.md
Labels: documentation

#95808 adding_a_cask.md: remove < and >
  doc/development/adding_a_cask.md
Labels: documentation

#95415 Update sharemouse.rb
  Casks/sharemouse.rb
Labels: ci-skip-appcast

#95784 Update messenger from 81.6.118,261169871 to 83.5.128,262535382
  Casks/messenger.rb
Labels: ci-skip-appcast

#96179 app_not_upgrading.md: smaller image
  doc/faq/app_not_upgrading.md
Labels: documentation

#96394 Update boxcryptor.rb
  Casks/boxcryptor.rb
Labels: ci-skip-appcast

#96415 Update `url do` example.
  doc/cask_language_reference/stanzas/url.md
Labels: documentation

#96725 CONTRIBUTING.md: deprecate cask-repair
  CONTRIBUTING.md
Labels: documentation

#96442 README: reporting bugs: not included in upgrade
  README.md
Labels: documentation

#96440 Rename the_app_cant_be_opened.md to app_cant_be_opened.md
  doc/faq/app_cant_be_opened.md
Labels: documentation

#96438 app_not_upgrading.md: add alt text and make size explicit
  doc/faq/app_not_upgrading.md
Labels: documentation

#93374 Added SuperSlicer Stable to Homebrew
  Casks/superslicer.rb
Labels: ci-syntax-only

#96454 menubar-stats: add livecheck
  Casks/menubar-stats.rb
Labels: ci-retry

#96752 jbidwatcher: add livecheck
  Casks/jbidwatcher.rb
Labels: ci-retry

#96024 Add BlueWallet.app v6.0.1
  Casks/bluewallet.rb
Labels: awaiting user reply

#96091 Add python dependency to google-cloud-sdk
  Casks/google-cloud-sdk.rb
Labels: awaiting user reply

#96763 Update nomachine from 7.0.209_4 to 7.0.211_1
  Casks/nomachine.rb
Labels: ci-skip-install

#96517 phew: add livecheck
  Casks/phew.rb
Labels: ci-syntax-only

#96652 Update streamlink-twitch-gui to 1.11.0
  Casks/streamlink-twitch-gui.rb
Labels: ci-skip-install

#96778 bestres: add livecheck
  Casks/bestres.rb
Labels: ci-syntax-only

#96779 captin: add livecheck
  Casks/captin.rb
Labels: ci-syntax-only

#96777 bathyscaphe: add livecheck
  Casks/bathyscaphe.rb
Labels: ci-syntax-only

#96780 chatmate-for-facebook: add livecheck
  Casks/chatmate-for-facebook.rb
Labels: ci-syntax-only

#96781 chatmate-for-whatsapp: add livecheck
  Casks/chatmate-for-whatsapp.rb
Labels: ci-syntax-only

#96792 dropshare: add livecheck
  Casks/dropshare.rb
Labels: ci-syntax-only

#96794 faxbot: add livecheck
  Casks/faxbot.rb
Labels: ci-syntax-only

#96776 apptrap: add livecheck
  Casks/apptrap.rb
Labels: ci-syntax-only

#96796 focused: add livecheck
  Casks/focused.rb
Labels: ci-syntax-only

#96799 gemini: add livecheck
  Casks/gemini.rb
Labels: ci-syntax-only

#96800 ghosttile: add livecheck
  Casks/ghosttile.rb
Labels: ci-syntax-only

#96801 haptic-touch-bar: add livecheck
  Casks/haptic-touch-bar.rb
Labels: ci-syntax-only

#96802 hubstaff: add livecheck
  Casks/hubstaff.rb
Labels: ci-syntax-only

#96803 ibettercharge: add livecheck
  Casks/ibettercharge.rb
Labels: ci-syntax-only

#96804 imazing-mini: add livecheck
  Casks/imazing-mini.rb
Labels: ci-syntax-only

#96808 jitsi: add livecheck
  Casks/jitsi.rb
Labels: ci-syntax-only

#96809 messenger-unofficial: add livecheck
  Casks/messenger-unofficial.rb
Labels: ci-syntax-only

#96854 Update ipepresenter from 7.2.22 to 7.2.23
  Casks/ipepresenter.rb
Labels: ci-skip-appcast

#96276 Added CircuitJS1 app
  Casks/circuitjs1.rb
Labels: awaiting user reply

#96896 playmemories-home: add livecheck
  Casks/playmemories-home.rb
Labels: ci-skip-install

#96906 lego-mindstorms-ev3: add livecheck
  Casks/lego-mindstorms-ev3.rb
Labels: ci-skip-install

#96934 Create exceptions_notability_threshold.md
  doc/faq/exceptions_notability_threshold.md
Labels: documentation

#96962 Add cask "digidna-silicon" v1.0.3
  Casks/silicon.rb
Labels: ci-syntax-only

#97006 fme: add livecheck
  Casks/fme.rb
Labels: ci-skip-install

#97030 adobe-creative-cloud: fix brew style.
  Casks/adobe-creative-cloud.rb
Labels: ci-syntax-only

#97051 Update chromium from 838550 to 839551
  Casks/chromium.rb
Labels: ci-skip-appcast

#97074 Update wechat from 2.5.0,15735 to 2.6.0,16795
  Casks/wechat.rb
Labels: ci-skip-appcast
