Repository Homebrew/homebrew-cask, pull requests merged in 2021-05, with the labels that each got.

#104857 Update webcatalog
  Casks/webcatalog.rb
Labels: automerge-skip

#104856 Update rubymine from 2021.1,211.6693.118 to 2021.1.1,211.7142.41
  Casks/rubymine.rb
Labels: automerge-skip

#104855 Update intellij-idea from 2021.1,211.6693.111 to 2021.1.1,211.7142.45
  Casks/intellij-idea.rb
Labels: automerge-skip

#104852 Update versions from 1.4.1-1144 to 1.4.4,1147 and add livecheck
  Casks/versions.rb
Labels: automerge-skip

#104851 Update dropbox-passwords from 7.2.36 to 8.2.12 and add livecheck
  Casks/dropbox-passwords.rb
Labels: automerge-skip

#104848 Update firefly from 1.0.0 to 1.1.0
  Casks/firefly.rb
Labels: automerge-skip

#104844 Update nextcloud from 3.2.0 to 3.2.1
  Casks/nextcloud.rb
Labels: automerge-skip

#104841 Update modern-csv from 1.3.24 to 1.3.26
  Casks/modern-csv.rb
Labels: automerge-skip

#104836 Update timeular from 3.8.0 to 3.9.1 and add livecheck
  Casks/timeular.rb
Labels: automerge-skip

#104830 Update spotify from 1.1.57.443.ga029a6c4,1.1.57.443.ga029a6c4-46 to 1.1.58.820.g2ae50076,1.1.58.820.g2ae50076-37
  Casks/spotify.rb
Labels: automerge-skip

#104858 grandtotal: update to 7.0.6
  Casks/grandtotal.rb
Labels: automerge-skip

#104816 Update datagrip from 2021.1,211.6693.68 to 2021.1.1,211.7142.37
  Casks/datagrip.rb
Labels: automerge-skip

#104878 Update flock from 2.2.472 to 2.2.494 and add livecheck
  Casks/flock.rb
Labels: automerge-skip

#104877 Update aircall from 2.9.0 to 2.15.3 and add livecheck
  Casks/aircall.rb
Labels: automerge-skip

#104876 Update axe-edit-iii from 1.08.12 to 1.08.13
  Casks/axe-edit-iii.rb
Labels: automerge-skip

#104874 Update appcode from 2020.3.4,203.7717.57 to 2021.1,211.6693.150
  Casks/appcode.rb
Labels: automerge-skip

#104873 Update avast-secure-browser from 89.1.659.115 to 90.0.704.86
  Casks/avast-secure-browser.rb
Labels: automerge-skip

#104872 Update atlauncher from 3.4.3.2 to 3.4.3.3
  Casks/atlauncher.rb
Labels: automerge-skip

#104870 Update alfaview from 8.16.0 to 8.17.0
  Casks/alfaview.rb
Labels: automerge-skip

#104869 Update adobe-air from 33.1.1.444 to 33.1.1.476
  Casks/adobe-air.rb
Labels: automerge-skip

#104868 Update activedock from 2.87,2097 to 2.88,2098
  Casks/activedock.rb
Labels: automerge-skip

#104867 Update acorn from 7.0.2,15785 to 7.0.3,15840
  Casks/acorn.rb
Labels: automerge-skip

#104866 Update accordance from 13.1.6 to 13.1.7
  Casks/accordance.rb
Labels: automerge-skip

#104864 Update 115browser from 24.1.0.13 to 24.1.0.13
  Casks/115browser.rb
Labels: automerge-skip

#104860 Update impactor from 0.9.53 to 0.9.54
  Casks/impactor.rb
Labels: automerge-skip

#104859 Update qownnotes from 21.4.4 to 21.4.6
  Casks/qownnotes.rb
Labels: automerge-skip

#104853 nndd: remove
  Casks/nndd.rb
Labels: automerge-skip, marked for removal/rejection

#104838 Update quip from 7.31.1 to 7.34.3 and add livecheck
  Casks/quip.rb
Labels: automerge-skip

#104835 Update vrew from 0.7.0 to 0.8.4 and add livecheck
  Casks/vrew.rb
Labels: automerge-skip

#104834 Update tempo from 5.5.4 to 5.14.0 and add livecheck
  Casks/tempo.rb
Labels: automerge-skip

#104832 Update intellij-idea-ce from 2021.1 to 2021.1.1
  Casks/intellij-idea-ce.rb
Labels: automerge-skip

#104831 wechat 3.0.2.18,18041
  Casks/wechat.rb
Labels: automerge-skip

#104821 Update airfoil from 5.10.2 to 5.10.3
  Casks/airfoil.rb
Labels: automerge-skip

#104822 element: update to 1.7.26
  Casks/element.rb
Labels: automerge-skip

#104823 Update metasploit from 6.0.42,20210428102832 to 6.0.43,20210430102818
  Casks/metasploit.rb
Labels: automerge-skip

#104825 Update microsoft-edge from 90.0.818.49 to 90.0.818.51
  Casks/microsoft-edge.rb
Labels: automerge-skip

#104826 Update nosql-workbench from 2.2.0 to 3.0.0
  Casks/nosql-workbench.rb
Labels: automerge-skip

#104879 Update foobar2000 from 2.2.17 to 2.2.18
  Casks/foobar2000.rb
Labels: automerge-skip

#104861 logisim: development suspended indefinitely on 11 Oct 2014
  Casks/logisim.rb
Labels: automerge-skip

#104846 devonagent: add livecheck
  Casks/devonagent.rb
Labels: automerge-skip

#104845 sensei: add livecheck
  Casks/sensei.rb
Labels: automerge-skip

#104843 vanilla: add livecheck
  Casks/vanilla.rb
Labels: automerge-skip

#104817 Update checkra1n from 0.12.2 to 0.12.3
  Casks/checkra1n.rb
Labels: automerge-skip

#104818 Update Clash-For-Windows From 0.15.4 to 0.15.5
  Casks/clash-for-windows.rb
Labels: automerge-skip

#104819 Update burp-suite from 2021.4.2 to 2021.5
  Casks/burp-suite.rb
Labels: automerge-skip

#104824 Update one-switch from 1.18,295 to 1.19,308
  Casks/one-switch.rb
Labels: automerge-skip

#104833 writemapper: add livecheck
  Casks/writemapper.rb
Labels: automerge-skip

#104839 river-sparkle: add livecheck
  Casks/river-sparkle.rb
Labels: automerge-skip

#104840 pomello: add livecheck
  Casks/pomello.rb
Labels: automerge-skip

#104842 zotero: add livecheck
  Casks/zotero.rb
Labels: automerge-skip

#104780 Upgrade TradingView.app to 1.0.0-beta.3, new URL's and livecheck.
  Casks/tradingview.rb
Labels: automerge-skip

#104799 Add description to SpiderOakOne
  Casks/spideroakone.rb
Labels: automerge-skip

#104815 Update OS compatability for Tuple package
  Casks/tuple.rb
Labels: automerge-skip

#104896 Delete wakeonlan.rb
  Casks/wakeonlan.rb
Labels: marked for removal/rejection

#104828 Added intel/m1 detection for Miro
  Casks/miro.rb
Labels: automerge-skip

#104929 hubic: remove as hubiC service was discontinued
  Casks/hubic.rb
Labels: marked for removal/rejection

#104925 swift-explorer: remove
  Casks/swift-explorer.rb
Labels: marked for removal/rejection

#104910 vrep: remove as discontinued on Nov 2019 and v3.6.0 URL doesn't exist anymore
  Casks/vrep.rb
Labels: marked for removal/rejection

#104785 update syntax-highlight from v1.0.b31 to v2.0.3
  Casks/syntax-highlight.rb
  audit_exceptions/github_prerelease_allowlist.json
Labels: automerge-skip

#104875 Update avocode from 4.13.1 to 4.13.2
  Casks/avocode.rb
Labels: automerge-skip

#104871 Update amazon-workspaces from 3.1.6.1840 to 3.1.7.1881
  Casks/amazon-workspaces.rb
Labels: automerge-skip

#104865 Update 8bitdo-ultimate-software from 2.0.0 to 2.0.2
  Casks/8bitdo-ultimate-software.rb
Labels: automerge-skip

#104863 Update 5kplayer from 6.5.0,5000 to 6.8.0,5000
  Casks/5kplayer.rb
Labels: automerge-skip

#104827 Update sound-control from 2.5.0,5156 to 2.6.0,4297
  Casks/sound-control.rb
Labels: automerge-skip

#104970 Add TabTopus.app Cask
  Casks/tabtopus.rb
Labels: automerge-skip, new cask

#104891 duckstation: delete
  Casks/duckstation.rb
Labels: marked for removal/rejection

#104829 Add Recut v1.1.2
  Casks/recut.rb
Labels: new cask

#104926 Add Shield.app v1.0.1
  Casks/shield.rb
Labels: new cask

#105033 add Jellyfin Media Player.app v1.5.0
  Casks/jellyfin-media-player.rb
Labels: new cask

#104883 adoptopenjdk.rb: remove mention of external tap
  Casks/adoptopenjdk.rb
Labels: awaiting maintainer feedback

#104820 Add Specter.app v1.3.1
  Casks/specter.rb
Labels: new cask

#104173 Add ILSpy.app v7.0-rc1
  Casks/ilspy.rb
Labels: new cask

#104964 Adding Cryptonomic Galleon cask.
  Casks/cryptonomic-galleon.rb
Labels: new cask

#105094 Add cask "sbarex-qlmarkdown"
  Casks/sbarex-qlmarkdown.rb
Labels: new cask

#105100 Add Vitals.app v0.3.0
  Casks/vitals.rb
Labels: new cask

#104797 Add IRPF2021 v1.3
  Casks/irpf2021.rb
Labels: new cask

#105147 Add SiYuan.app v1.1.83
  Casks/siyuan.rb
Labels: new cask

#104914 Add Crescendo.app v1.0.4
  Casks/crescendo.rb
Labels: new cask

#105145 meshcommander: remove due to dead Bintray download URL
  Casks/meshcommander.rb
Labels: marked for removal/rejection

#105157 Add Mixed In Key 10.0.0.4394
  Casks/mixed-in-key.rb
Labels: new cask

#105206 adventure: remove as download/appcast are dead links
  Casks/adventure.rb
Labels: marked for removal/rejection

#105309 change url of depends_on macos
  doc/reporting_bugs/wrong_number_of_arguments_error.md
Labels: automerge-skip

#105162 Add new cask mütesync 4.3.0
  Casks/mutesync.rb
Labels: new cask

#104184 Update printrun from 1.6.0 to 2.0.0rc8
  Casks/printrun.rb
  Casks/pronterface.rb
Labels: automerge-skip

#105314 revisions: remove as dead download link and app will stop working soon
  Casks/revisions.rb
Labels: marked for removal/rejection

#105353 family-tree-builder: remove
  Casks/family-tree-builder.rb
Labels: marked for removal/rejection

#105467 spideroak-share: remove
  Casks/spideroak-share.rb
Labels: marked for removal/rejection

#104738 Add RDM.app v2.5.0
  Casks/usr-sse2-rdm.rb
Labels: automerge-skip, ci-syntax-only, new cask

#104514 Add depthmapX v.0.8.0
  Casks/depthmapx.rb
Labels: automerge-skip, ci-syntax-only, new cask

#105465 Update google-drive from 46.0.3.0 to 47.0.19 and add livecheck
  Casks/google-drive.rb
Labels: ci-skip-install

#105487 Add VitalSigns.app v3.0.10
  Casks/vitalsigns.rb
Labels: new cask

#105516 Update canva from 1.21.0 to 1.22.0
  Casks/canva.rb
Labels: ci-syntax-only

#105496 workflows/triage: auto-label `bump-cask-pr`
  .github/workflows/triage.yml
Labels: automerge-skip

#105555 Update microsoft-excel from 16.48.21041102 to 16.49.21050901
  Casks/microsoft-excel.rb
Labels: bump-cask-pr

#105559 Update metasploit from 6.0.44,20210510102804 to 6.0.44,20210511102754
  Casks/metasploit.rb
Labels: bump-cask-pr

#105558 Update microsoft-word from 16.48.21041102 to 16.49.21050901
  Casks/microsoft-word.rb
Labels: bump-cask-pr

#105563 Update balenaetcher from 1.5.117 to 1.5.120
  Casks/balenaetcher.rb
Labels: bump-cask-pr

#105567 Update microsoft-outlook from 16.48.21041102 to 16.49.21050901
  Casks/microsoft-outlook.rb
Labels: bump-cask-pr

#105568 Update brave-browser from 90.1.24.82,124.82 to 90.1.24.84,124.84
  Casks/brave-browser.rb
Labels: bump-cask-pr

#105570 audiobookbinder: remove
  Casks/audiobookbinder.rb
Labels: marked for removal/rejection

#105571 Update itch from 25.4.1 to 25.5.1
  Casks/itch.rb
Labels: bump-cask-pr

#105572 Update amazon-chime from 4.39.8384 to 4.39.8497
  Casks/amazon-chime.rb
Labels: bump-cask-pr

#105574 Update axe-edit-iii from 1.08.13 to 1.08.14
  Casks/axe-edit-iii.rb
Labels: bump-cask-pr

#105579 github_prerelease_allowlist: add seaglass
  audit_exceptions/github_prerelease_allowlist.json
Labels: automerge-skip

#105580 Update clicker-for-youtube from 1.11,42 to 1.13,44
  Casks/clicker-for-youtube.rb
Labels: bump-cask-pr

#105581 Update dingtalk from 6.0.12.7 to 6.0.12.8
  Casks/dingtalk.rb
Labels: bump-cask-pr

#105582 Update flock from 2.2.494 to 2.2.496
  Casks/flock.rb
Labels: bump-cask-pr

#105583 Update loom from 0.78.2 to 0.79.1
  Casks/loom.rb
Labels: bump-cask-pr

#105587 Update signal from 5.0.0 to 5.1.0
  Casks/signal.rb
Labels: bump-cask-pr

#105589 Update wire from 3.24.4059 to 3.25.4095
  Casks/wire.rb
Labels: bump-cask-pr

#105584 cellery: remove
  Casks/cellery.rb
Labels: marked for removal/rejection

#105591 Update twine from 2.3.13 to 2.3.14
  Casks/twine.rb
Labels: bump-cask-pr

#105592 Update pitch from 1.25.2,1470873 to 1.26.0,1502213
  Casks/pitch.rb
Labels: bump-cask-pr

#105596 adding_a_cask: various updates
  doc/development/adding_a_cask.md
Labels: automerge-skip, documentation

#105625 Update qqmusic from 7.6.0,69820 to 7.6.5,69866
  Casks/qqmusic.rb
Labels: bump-cask-pr

#105624 Update openwebstart from 1.3.3 to 1.4.0
  Casks/openwebstart.rb
Labels: bump-cask-pr

#105626 updated chromedriver deprecated links
  Casks/chromedriver.rb
Labels: awaiting user reply

#105638 Update eloston-chromium from 90.0.4430.93-1.1_x86-64 to 90.0.4430.212-1.1_x86-64
  Casks/eloston-chromium.rb
Labels: bump-cask-pr

#105640 Update raycast from 1.13.0 to 1.14.0
  Casks/raycast.rb
Labels: bump-cask-pr

#105627 Update yuque from 0.7.14 to 0.8.11
  Casks/yuque.rb
Labels: bump-cask-pr

#105643 Update qownnotes from 21.5.1 to 21.5.2
  Casks/qownnotes.rb
Labels: bump-cask-pr

#105633 Add Menu Bar Splitter.app v2.0
  Casks/menu-bar-splitter.rb
Labels: new cask

#105649 Update dropbox from 121.4.4267 to 122.4.4867
  Casks/dropbox.rb
Labels: bump-cask-pr

#105636 Sync triage workflow between cask repos
  .github/actions/sync/templates.rb
  .github/workflows/review.yml
  .github/workflows/triage.yml
Labels: automerge-skip, ci-syntax-only

#105644 Update anka-build-cloud-controller-and-registry from 1.15.0-c69e2600 to 1.16.0-05de337e
  Casks/anka-build-cloud-controller-and-registry.rb
Labels: bump-cask-pr

#105645 Update anka-build-cloud-registry from 1.15.0-a88b7bc to 1.16.0-25e4cad
  Casks/anka-build-cloud-registry.rb
Labels: bump-cask-pr

#105650 Update gitkraken from 7.5.5 to 7.6.0
  Casks/gitkraken.rb
Labels: bump-cask-pr

#105641 Add Shortcutor 2020.4.1
  Casks/shortcutor.rb
Labels: new cask

#105575 Update badlion-client from 3.1.9 to 3.2.0
  Casks/badlion-client.rb
Labels: bump-cask-pr, ci-syntax-only

#105680 opennx: remove
  Casks/opennx.rb
Labels: marked for removal/rejection

#105681 Add WALTR PRO
  Casks/waltr-pro.rb
Labels: new cask

#105682 Update keeweb from 1.18.3 to 1.18.4
  Casks/keeweb.rb
Labels: bump-cask-pr

#105684 Update bitwarden from 1.25.1 to 1.26.3
  Casks/bitwarden.rb
Labels: bump-cask-pr

#105686 Update decrediton from 1.6.2 to 1.6.3
  Casks/decrediton.rb
Labels: bump-cask-pr

#105690 Update anaconda from 2020.11 to 2021.04
  Casks/anaconda.rb
Labels: bump-cask-pr

#105693 Update kicad from 5.1.9-0 to 5.1.10-1
  Casks/kicad.rb
Labels: bump-cask-pr

#105695 Update burp-suite from 2021.5 to 2021.5.1
  Casks/burp-suite.rb
Labels: bump-cask-pr

#105702 Update zettlr from 1.8.8 to 1.8.9
  Casks/zettlr.rb
Labels: bump-cask-pr

#105698 Update skype from 8.71.0.45 to 8.72.0.82
  Casks/skype.rb
Labels: bump-cask-pr

#105701 Update vuescan from 9.7.53 to 9.7.54
  Casks/vuescan.rb
Labels: bump-cask-pr

#105700 Improve WALTR PRO zap stanza
  Casks/waltr-pro.rb
Labels: automerge-skip

#105703 Update blitz from 1.14.11 to 1.14.13
  Casks/blitz.rb
Labels: bump-cask-pr

#105704 Update syntax-highlight from 2.0.4 to 2.0.5
  Casks/syntax-highlight.rb
Labels: bump-cask-pr

#105707 Update microsoft-edge from 90.0.818.56 to 90.0.818.62
  Casks/microsoft-edge.rb
Labels: bump-cask-pr

#105708 Update propresenter from 7.5,117768207 to 7.5.1,117768465
  Casks/propresenter.rb
Labels: bump-cask-pr

#105710 Update carbon-copy-cloner from 5.1.26.6180 to 5.1.27.6193
  Casks/carbon-copy-cloner.rb
Labels: bump-cask-pr

#105709 Update backblaze from 7.0.2.494 to 7.0.2.496
  Casks/backblaze.rb
Labels: bump-cask-pr

#105689 Change the name of the unofficial rabbitmq cask
  Casks/jpadilla-rabbitmq.rb
Labels: awaiting user reply

#105688 Change the name of the unofficial redis cask
  Casks/jpadilla-redis.rb
Labels: awaiting user reply

#104677 Update fawkes from 0.3.1 to 1.0
  Casks/fawkes.rb
Labels: bump-cask-pr, ci-syntax-only
