Repository Homebrew/homebrew-cask, pull requests merged in 2021-04, with the labels that each got.

#102948 Update `url do` docs.
  doc/cask_language_reference/stanzas/url.md
Labels: documentation

#103197 mactex: update depends_on and zap
  Casks/mactex.rb
Labels: ci-skip-install

#103135 Update google-drive from 45.0.12.0 to 46.0
  Casks/google-drive.rb
Labels: ci-skip-install

#103206 Update google-drive from 46.0 to 46.0.3.0
  Casks/google-drive.rb
Labels: ci-skip-install

#103364 Documentation: Fix broken link
  USAGE.md
Labels: documentation

#103413 multifirefox: add livecheck
  Casks/multifirefox.rb
Labels: ci-skip-appcast

#103432 Update cleanmymac from 4.8.2,40802.0.2103291406 to 4.8.2,40802.0.2104081317
  Casks/cleanmymac.rb
Labels: ci-skip-install

#103612 Update tripmode from 3.0.3,1101 to 3.0.4,1113
  Casks/tripmode.rb
Labels: ci-skip-appcast

#103744 Update prey from 1.9.9 to 1.9.10
  Casks/prey.rb
Labels: ci-skip-install

#104174 Fix broken link for documented exception in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#104402 Update virtualbox-extension-pack from 6.1.18 to 6.1.20
  Casks/virtualbox-extension-pack.rb
Labels: ci-skip-install

#104468 simple version bump from 3.18.1 to 3.18.2
  Casks/qgis.rb
Labels: upstream

#104686 Update miro from 0.5.2 to 0.5.3
  Casks/miro.rb
Labels: automerge-skip

#104704 Update musicbrainz-picard from 2.6.1 to 2.6.2
  Casks/musicbrainz-picard.rb
Labels: automerge-skip

#104701 exist-db: Move URL from Bintray to GitHub Releases
  Casks/exist-db.rb
Labels: automerge-skip

#104674 Update arq from 7.5.3 to 7.5.6
  Casks/arq.rb
Labels: automerge-skip

#104705 Update chalk from 1.6.8 to 1.6.9 and add livecheck
  Casks/chalk.rb
Labels: automerge-skip

#104694 Update videofusion from 1.2.3.0 to 1.2.5.0
  Casks/videofusion.rb
Labels: automerge-skip

#104666 Update sia-ui from 1.5.3 to 1.5.6
  Casks/sia-ui.rb
Labels: automerge-skip

#104706 Update propresenter from 7.4.2,117703186 to 7.5,117768207
  Casks/propresenter.rb
Labels: automerge-skip

#104708 cheatsheet: add livecheck
  Casks/cheatsheet.rb
Labels: automerge-skip

#104707 chatology: update to final version 1.2.5 and mark discontinued
  Casks/chatology.rb
Labels: automerge-skip

#104711 cliqz: remove
  Casks/cliqz.rb
Labels: automerge-skip, marked for removal/rejection

#104719 Update twobird from 1.0.27 to 1.0.30 and add livecheck
  Casks/twobird.rb
Labels: automerge-skip

#104717 Update debookee from 8.0.3,3204 to 8.0.4,3207 and add livecheck
  Casks/debookee.rb
Labels: automerge-skip

#104716 cuteclips: remove
  Casks/cuteclips.rb
Labels: automerge-skip, marked for removal/rejection

#104715 cryptomator: add livecheck
  Casks/cryptomator.rb
Labels: automerge-skip

#104713 commandq: add livecheck
  Casks/commandq.rb
Labels: automerge-skip

#104714 Update genymotion from 3.2.0 to 3.2.1
  Casks/genymotion.rb
Labels: automerge-skip

#104720 Update trainerroad from 2020.50.0.118 to 2021.16.0.130 and add livecheck
  Casks/trainerroad.rb
Labels: automerge-skip

#104710 clipbuddy: remove
  Casks/clipbuddy.rb
Labels: automerge-skip, marked for removal/rejection

#104727 Update trilium-notes from 0.46.9 to 0.47.2
  Casks/trilium-notes.rb
Labels: automerge-skip

#104726 transmit: add livecheck
  Casks/transmit.rb
Labels: automerge-skip

#104723 toptracker: add livecheck
  Casks/toptracker.rb
Labels: automerge-skip

#104722 Update torguard from 4.3.0 to 4.6.0 and add livecheck
  Casks/torguard.rb
Labels: automerge-skip

#104721 Update toinane-colorpicker from 2.0.3 to 2.0.5
  Casks/toinane-colorpicker.rb
Labels: automerge-skip

#104724 tracks-live: remove since discontinued and last update 2017
  Casks/tracks-live.rb
Labels: automerge-skip, marked for removal/rejection

#104728 Update bootstrap-studio from 5.5.3 to 5.6.2 and add livecheck
  Casks/bootstrap-studio.rb
Labels: automerge-skip

#104729 Update kitty from 0.20.1 to 0.20.2
  Casks/kitty.rb
Labels: automerge-skip

#104730 cakebrew: add livecheck
  Casks/cakebrew.rb
Labels: automerge-skip

#104731 Update freecad from 0.19.2,24276 to 0.19.2,24291
  Casks/freecad.rb
Labels: automerge-skip

#104733 Update caprine from 2.52.3 to 2.52.4
  Casks/caprine.rb
Labels: automerge-skip

#104734 Update catch from 2.0 to 2.0.1
  Casks/catch.rb
Labels: automerge-skip

#104744 latexit: add livecheck
  Casks/latexit.rb
Labels: automerge-skip

#104743 keyboard-maestro: add livecheck
  Casks/keyboard-maestro.rb
Labels: automerge-skip

#104745 Update blitz from 1.14.4 to 1.14.5
  Casks/blitz.rb
Labels: automerge-skip

#104747 Update mullvadvpn from 2021.2 to 2021.3
  Casks/mullvadvpn.rb
Labels: automerge-skip

#104750 Add arm64 version for clash-for-windows
  Casks/clash-for-windows.rb
Labels: automerge-skip

#104751 beatunes: update to 5.2.21
  Casks/beatunes.rb
Labels: automerge-skip

#103043 Add HancomWord.pkg
  Casks/hancom-word.rb
Labels: awaiting user reply, stale

#104732 Update camtasia from 2020.0.18 to 2021.0.0 and add livecheck
  Casks/camtasia.rb
Labels: automerge-skip

#104757 Update alfred from 4.3.3,1226 to 4.3.4,1229
  Casks/alfred.rb
Labels: automerge-skip

#104749 Update carbon-copy-cloner from 5.1.26.6179 to 5.1.26.6180
  Casks/carbon-copy-cloner.rb
Labels: automerge-skip

#104742 Update cleanmymac from 4.8.2,40802.0.2103291406 to 4.8.3,40803.0.2104261825
  Casks/cleanmymac.rb
Labels: automerge-skip

#104740 Update typora from 0.10.4 to 0.10.6
  Casks/typora.rb
Labels: automerge-skip

#104739 Update telegram-desktop from 2.7.2 to 2.7.3
  Casks/telegram-desktop.rb
Labels: automerge-skip

#104737 Update http-toolkit from 1.2.2 to 1.3.0
  Casks/http-toolkit.rb
Labels: automerge-skip

#104758 Update BBEdit to 13.5.6
  Casks/bbedit.rb
Labels: automerge-skip

#104756 Update opera from 75.0.3969.243 to 76.0.4017.94
  Casks/opera.rb
Labels: automerge-skip

#104755 Update tutanota from 3.82.18 to 3.83.0
  Casks/tutanota.rb
Labels: automerge-skip

#104754 Update stoplight-studio from 2.3.0,5666.git-aa6309c to 2.3.0,5696.git-feef2f0
  Casks/stoplight-studio.rb
Labels: automerge-skip

#104753 Update telegram from 7.7.215778 to 7.7.215786
  Casks/telegram.rb
Labels: automerge-skip

#104736 Update moom from 3.2.21,3317 to 3.2.22,3323
  Casks/moom.rb
Labels: automerge-skip

#104712 Update codelite from 14.0.0 to 15.0.0 and add livecheck
  Casks/codelite.rb
Labels: automerge-skip

#104773 Update insomnia from 2021.2.2 to 2021.3.0
  Casks/insomnia.rb
Labels: automerge-skip

#104770 Update raycast from 1.12.0 to 1.13.0
  Casks/raycast.rb
Labels: automerge-skip

#104765 Update nault from 1.10.5 to 1.11.1
  Casks/nault.rb
Labels: automerge-skip

#104725 transmit-disk: remove as discontinued and Cask not maintained
  Casks/transmit-disk.rb
Labels: automerge-skip, marked for removal/rejection

#104735 grid: add livecheck
  Casks/grid.rb
Labels: automerge-skip

#104746 Update github from 2.7.2-5b94c877 to 2.8.0-853674e1
  Casks/github.rb
Labels: automerge-skip

#104776 Update telegram-desktop from 2.7.3 to 2.7.4
  Casks/telegram-desktop.rb
Labels: automerge-skip

#104775 Update whatsapp from 2.2114.9 to 2.2114.10
  Casks/whatsapp.rb
Labels: automerge-skip

#104774 Update brave-browser from 90.1.23.73,123.73 to 90.1.23.75,123.75
  Casks/brave-browser.rb
Labels: automerge-skip

#104769 Update orka from 1.5.0 to 1.5.3 and add livecheck
  Casks/orka.rb
Labels: automerge-skip

#104768 Netbeans CPP, Java EE, Java SE: remove
  Casks/netbeans-cpp.rb
  Casks/netbeans-java-ee.rb
  Casks/netbeans-java-se.rb
Labels: automerge-skip, marked for removal/rejection

#104767 Update neo4j from 1.3.11 to 1.4.3 and add livecheck
  Casks/neo4j.rb
Labels: automerge-skip

#104764 lingo: remove
  Casks/lingo.rb
Labels: automerge-skip, marked for removal/rejection

#104761 exist-db: Constrain to compatible versions
  Casks/exist-db.rb
Labels: automerge-skip

#104760 Improve melonDS 0.9.2 Cask
  Casks/melonds.rb
Labels: automerge-skip

#104766 Update lingon-x from 8.2 to 8.2.1
  Casks/lingon-x.rb
Labels: automerge-skip

#104782 Update permute from 3.6.2,2410 to 3.6.3,2417
  Casks/permute.rb
Labels: automerge-skip

#104781 Update downie from 4.2.3,4238 to 4.2.4,4240
  Casks/downie.rb
Labels: automerge-skip

#104778 Update flipper from 0.86.0 to 0.87.0
  Casks/flipper.rb
Labels: automerge-skip

#104759 wechat 3.0.2.17,18028
  Casks/wechat.rb
Labels: automerge-skip

#104794 Update aerial from 2.3.1 to 2.3.2
  Casks/aerial.rb
Labels: automerge-skip

#104463 Update teamviewer from 15.16.8 to 15.17.6
  Casks/teamviewer.rb
Labels: automerge-skip

#104791 Update metasploit from 6.0.42,20210427102916 to 6.0.42,20210428102832
  Casks/metasploit.rb
Labels: automerge-skip

#104789 canva: update to 1.21.1
  Casks/canva.rb
Labels: automerge-skip

#104793 Update helo from 1.4.0 to 1.5.0
  Casks/helo.rb
Labels: automerge-skip

#104788 JOSM version bump
  Casks/josm.rb
Labels: automerge-skip

#104787 Update stremio from 4.4.135 to 4.4.137
  Casks/stremio.rb
Labels: automerge-skip

#104783 Update understand from 6.0.1060 to 6.0.1063
  Casks/understand.rb
Labels: automerge-skip

#104777 Update xampp from 7.4.15,0 to 8.0.3-0 and add livecheck
  Casks/xampp.rb
Labels: automerge-skip

#104796 Update yakyak from 1.5.11.2 to 1.5.11.4
  Casks/yakyak.rb
Labels: automerge-skip

#104808 Update vagrant from 2.2.15 to 2.2.16
  Casks/vagrant.rb
Labels: automerge-skip

#104805 Update eloston-chromium from 90.0.4430.85-1.1 to 90.0.4430.93-1.1
  Casks/eloston-chromium.rb
Labels: automerge-skip

#104804 Update dash from 6.0.4,974 to 6.0.5,976
  Casks/dash.rb
Labels: automerge-skip

#104800 unity-hub: add livecheck
  Casks/unity-hub.rb
Labels: automerge-skip

#104798 Update tutanota from 3.83.0 to 3.83.2
  Casks/tutanota.rb
Labels: automerge-skip

#104795 Add Invoker.app v2.4.0
  Casks/invoker.rb
Labels: automerge-skip, new cask

#104806 Description for Pure data package
  Casks/pd.rb
Labels: automerge-skip

#104803 Update virtualbox-extension-pack from 6.1.20 to 6.1.22
  Casks/virtualbox-extension-pack.rb
Labels: automerge-skip, ci-skip-install

#104801 Update evernote from 10.12.5,2564 to 10.12.6,2583
  Casks/evernote.rb
Labels: automerge-skip

#104813 Update outline-manager from 1.7.2 to 1.8.0
  Casks/outline-manager.rb
Labels: automerge-skip

#104812 Update netron to 4.9.1
  Casks/netron.rb
Labels: automerge-skip

#104811 Update calibre from 5.16.1 to 5.17.0
  Casks/calibre.rb
Labels: automerge-skip

#104810 Update betelguese from 1.0 to 1.1
  Casks/betelguese.rb
Labels: automerge-skip

#104809 Update insync from 3.3.8.40942 to 3.3.9.40955
  Casks/insync.rb
Labels: automerge-skip
