Repository Homebrew/homebrew-cask, pull requests merged in 2021-02, with the labels that each got.

#99254 prey: add livecheck, update caveats
  Casks/prey.rb
Labels: ci-skip-install

#99310 Add Gather.app v0.0.6
  Casks/gather.rb
Labels: ci-syntax-only

#99395 Update amazon-music.rb
  Casks/amazon-music.rb
Labels: ci-skip-install

#99319 Add Parsify Desktop v1.5.2
  Casks/parsify.rb
Labels: ci-syntax-only

#99544 Add Lightform.app v2.0.6.920
  Casks/lightform.rb
Labels: awaiting user reply

#99419 Rename google-drive-file-stream to google-drive
  Casks/google-drive-file-stream.rb
  Casks/google-drive.rb
Labels: ci-skip-install

#99432 Update iina from 1.1.2,128 to 1.2.0,129
  Casks/iina.rb
Labels: ci-syntax-only

#99951 mumble.rb: remove appcast
  Casks/mumble.rb
Labels: ci-syntax-only

#99542 zoomus.rb: trigger update
  Casks/zoomus.rb
Labels: ci-syntax-only

#99937 Kaleidoscope 2.4
  Casks/kaleidoscope.rb
  Casks/ksdiff.rb
Labels: awaiting user reply

#99964 Update android-platform-tools from 30.0.0 to 30.0.5
  Casks/android-platform-tools.rb
Labels: ci-syntax-only

#100100 installer.md: installer script: should never be used for interactive installations
  doc/cask_language_reference/stanzas/installer.md
Labels: documentation

#100099 Update android-platform-tools from 30.0.5,eabcd8b4b7ab518c6af9c941af8494072f17ec4b to 31.0.0,f62237c314a6bb80f574f0812e8109e16d52076d
  Casks/android-platform-tools.rb
Labels: ci-syntax-only

#100142 Delete rejected_casks.md
  doc/faq/rejected_casks.md
Labels: documentation

#100218 gpg-suite-no-mail: add description
  Casks/gpg-suite-no-mail.rb
Labels: ci-syntax-only

#100134 Add Pika.app v0.0.9
  Casks/pika.rb
Labels: awaiting user reply

#100139 Delete apps_with_malware.md
  doc/faq/apps_with_malware.md
Labels: documentation

#100140 Delete exceptions_notability_threshold.md
  doc/faq/exceptions_notability_threshold.md
Labels: documentation

#100141 Delete not_a_discoverability_service.md
  doc/faq/not_a_discoverability_service.md
Labels: documentation

#100138 adding_a_cask: move Finding a Home For Your Cask
  doc/development/adding_a_cask.md
Labels: documentation

#100130 Add Infinity.app 1.0.0
  Casks/infinity.rb
Labels: awaiting user reply

#100234 Add Bluesnooze
  Casks/bluesnooze.rb
Labels: awaiting user reply

#100220 curl_error.md: update _stanza command
  doc/reporting_bugs/curl_error.md
Labels: documentation

#100357 Add ZuluFX 15.0.2
  Casks/zulufx.rb
Labels: awaiting user reply
