Repository Homebrew/homebrew-cask, pull requests merged in 2021-03, with the labels that each got.

#100465 Update chromium from 856554 to 858446
  Casks/chromium.rb
Labels: ci-syntax-only

#100401 Delete hacking.md
  doc/development/hacking.md
Labels: documentation

#100309 Add Bob Wallet v0.6.2
  Casks/kyokan-bob.rb
Labels: awaiting user reply

#100479 Update deeper from 2.6.1 to 2.6.5
  Casks/deeper.rb
Labels: ci-skip-appcast

#100549 Update deeper from 2.6.5 to 2.6.6
  Casks/deeper.rb
Labels: ci-skip-appcast

#100281 outline-manager: add livecheck and zap entries
  Casks/outline-manager.rb
Labels: awaiting user reply

#100696 adding_a_cask.md: fix rejected casks link
  doc/development/adding_a_cask.md
Labels: documentation

#100747 twine: adding zap stanza
  Casks/twine.rb
Labels: awaiting user reply

#100919 Add foobar2000.app v2.2.16
  Casks/foobar2000.rb
Labels: awaiting user reply

#101224 Update kafka-tool from 2.0.8 to 2.0.9
  Casks/kafka-tool.rb
Labels: ci-skip-install

#101223 Update token_reference.md
  doc/cask_language_reference/token_reference.md
Labels: documentation

#100725 google-drive: delete launchctl services only with zap
  Casks/google-drive.rb
Labels: ci-syntax-only

#101063 dnagedcom 3.1.3.8 (new formula)
  Casks/dnagedcom.rb
Labels: ci-syntax-only

#101244 Added Cinderella Geometry Software
  Casks/cinderella.rb
Labels: awaiting user reply

#100984 Add Celestia 1.62
  Casks/celestia.rb
Labels: awaiting user reply

#101394 boxcryptor: adding zap stanza
  Casks/boxcryptor.rb
Labels: ci-syntax-only

#101392 macjournal: adding zap stanza
  Casks/macjournal.rb
Labels: ci-syntax-only

#101716 cytoscape: add livecheck
  Casks/cytoscape.rb
Labels: ci-skip-install

#102098 pivy: add livecheck
  Casks/pivy.rb
Labels: ci-skip-install

#101396 Update cinderella from 3.0b.1989 to 3.0b.1999
  Casks/cinderella.rb
Labels: awaiting user reply

#102368 Update berrycast from 0.31.3 to 0.32.5
  Casks/berrycast.rb
Labels: ci-skip-install

#102414 manuskript: add livecheck
  Casks/manuskript.rb
  audit_exceptions/github_prerelease_allowlist.json
Labels: ci-skip-appcast

#102551 wavtap: add livecheck
  Casks/wavtap.rb
Labels: ci-skip-install

#102503 Add Betelguese.app 1.0
  Casks/betelguese.rb
Labels: awaiting user reply

#101474 Add xbar.app v2.0.33-beta
  Casks/xbar.rb
Labels: awaiting user reply

#102562 lbry: Update to v0.50.1, add shimscripts for lbrynet and lbry-first, add desc
  Casks/lbry.rb
Labels: awaiting user reply

#102784 Update Tipp10 to only install on macOS before Catalina
  Casks/tipp10.rb
Labels: awaiting user reply

#102871 Update boxcryptor from 2.39.1119 to 2.40.1234
  Casks/boxcryptor.rb
Labels: ci-syntax-only

#102695 Update tripmode from 3.0.0,1023 to 3.0.3,1101
  Casks/tripmode.rb
Labels: ci-syntax-only

#102659 Update birdfont from 4.12.2 to 4.14.3
  Casks/birdfont.rb
Labels: ci-skip-appcast
