Repository Homebrew/homebrew-cask, pull requests merged in 2021-01, with the labels that each got.

#97137 desc.md: hammer the point of marketing fluff
  doc/cask_language_reference/stanzas/desc.md
Labels: documentation

#97211 Update santa from 1.15 to 1.17
  Casks/santa.rb
Labels: ci-syntax-only

#97002 feat: add Stringz
  Casks/stringz.rb
Labels: ci-syntax-only

#97151 chromium: add livecheck
  Casks/chromium.rb
Labels: ci-skip-appcast

#97351 gobdokumente.rb: use sha256 :no_check
  Casks/gobdokumente.rb
Labels: ci-syntax-only

#97196 Added zap stanza for jenkins-menu
  Casks/jenkins-menu.rb
Labels: ci-syntax-only

#97353 Update chromium from 839551 to 840589
  Casks/chromium.rb
Labels: ci-skip-appcast

#97129 Updated zap items for amazon-music
  Casks/amazon-music.rb
Labels: ci-syntax-only

#97436 dosbox-x: add livecheck
  Casks/dosbox-x.rb
Labels: ci-syntax-only

#97484 Only run on all macOS versions if casks contain any of the supported ones.
  cmd/lib/ci_matrix.rb
  cmd/lib/generate-matrix.rb
Labels: ci-syntax-only

#97486 Add docs for `livecheck` stanza.
  doc/cask_language_reference/all_stanzas.md
  doc/cask_language_reference/livecheck.md
  doc/cask_language_reference/stanzas/appcast.md
Labels: ci-syntax-only, documentation

#97496 Update chromium from 840589 to 841343
  Casks/chromium.rb
Labels: ci-skip-appcast

#97261 Fix pkg and add sha256 for mbed-studio
  Casks/mbed-studio.rb
Labels: ci-syntax-only

#97499 Fix livecheck.md documentation issues
  doc/cask_language_reference/stanzas/livecheck.md
Labels: documentation

#97421 Add Ray.app 1.0.1
  Casks/ray.rb
Labels: awaiting user reply

#97521 Update prey from 1.9.3 to 1.9.8
  Casks/prey.rb
Labels: ci-skip-install

#97362 Update free-download-manager from 6.13.0 to 6.13.1
  Casks/free-download-manager.rb
Labels: ci-skip-appcast

#97660 cask_language_reference: stanza order: add livecheck
  doc/cask_language_reference/readme.md
Labels: documentation

#96895 melonDS 0.9.1 (new cask)
  Casks/melonds.rb
Labels: awaiting maintainer feedback

#98038 Add PiBar.app v1.1
  Casks/pibar.rb
Labels: awaiting user reply

#97752 heimdall-suite: add livecheck
  Casks/heimdall-suite.rb
Labels: ci-skip-install

#98114 Update bettertouchtool from 3.508,1646 to 3.534,1673
  Casks/bettertouchtool.rb
Labels: ci-skip-appcast

#97988 Update Tower from 6.1,258:9c97138e to 6.2,264:e552e274
  Casks/tower.rb
Labels: ci-skip-appcast

#98168 ptpwebcam 1.2.6 (new cask)
  Casks/ptpwebcam.rb
Labels: ci-syntax-only

#98365 deviceinfo.rb: no cross-platform in desc
  Casks/deviceinfo.rb
Labels: ci-syntax-only

#98351 my-budget.rb: remove marketing fluff
  Casks/my-budget.rb
Labels: ci-syntax-only

#98342 electron.rb: no cross-platform in desc
  Casks/electron.rb
Labels: ci-syntax-only

#98390 Update virtualbox-extension-pack from 6.1.16 to 6.1.18
  Casks/virtualbox-extension-pack.rb
Labels: ci-skip-install

#98429 clementine.rb: no cross-platform in desc
  Casks/clementine.rb
Labels: ci-skip-appcast

#98359 Update eudic-es from 4.0.1,2020-11-16 to 4.0.2,2020-12-20
  Casks/eudic-es.rb
Labels: awaiting user reply

#98454 Spotter
  Casks/spotter.rb
Labels: awaiting user reply

#98490 Update chromium from 842924 to 845727
  Casks/chromium.rb
Labels: ci-skip-appcast

#98491 Update android-studio to 4.1.2.0,201.7042882
  Casks/android-studio.rb
Labels: ci-syntax-only

#98528 app_cant_be_opened.md: mention --no-quarantine
  doc/faq/app_cant_be_opened.md
Labels: documentation

#98529 USAGE.md: add --no-quarantine
  USAGE.md
Labels: documentation

#98662 rejected_casks.md: include old java-development casks in "hard to maintain"
  doc/faq/rejected_casks.md
Labels: documentation

#98680 Update prey from 1.9.8 to 1.9.9
  Casks/prey.rb
Labels: ci-skip-install

#98976 android-sdk: minor updates
  Casks/android-sdk.rb
Labels: ci-syntax-only

#99080 Update Flux from 40.1 to 41.1
  Casks/flux.rb
Labels: ci-skip-appcast

#99090 forticlient: use offline installer & rewrite uninstall
  Casks/forticlient.rb
Labels: awaiting user reply

#99107 Fix pokerstars install url
  Casks/pokerstars.rb
Labels: awaiting user reply
